const nodeHtmlToImage = require('node-html-to-image');

/**
 * Generate a PNG image report for vehicle expenses.
 * @param {Array}  expenses  - rows from vehicle_expenses
 * @param {string} startDateStr - start date string (e.g. 01/04/2026)
 * @param {string} endDateStr - end date string (e.g. 15/04/2026)
 * @param {number} totalAmount - Total expense amount
 * @returns {Promise<Buffer>}
 */
async function generateExpenseImageReport(expenses, startDateStr, endDateStr, totalAmount) {
    const htmlTemplate = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            margin: 0;
            padding: 30px;
            background-color: #f8f9fa;
            color: #2d3436;
            width: 800px;
        }
        .header {
            background-color: #2c3e50;
            color: white;
            padding: 20px;
            border-radius: 12px 12px 0 0;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 28px;
            letter-spacing: 1px;
        }
        .header p {
            margin: 5px 0 0;
            font-size: 16px;
            opacity: 0.9;
        }
        .summary-bar {
            background-color: #fff;
            padding: 20px;
            border-bottom: 2px solid #eee;
            text-align: center;
        }
        .summary-label {
            font-size: 14px;
            color: #636e72;
            text-transform: uppercase;
            margin-bottom: 5px;
        }
        .summary-value {
            font-size: 24px;
            font-weight: bold;
            color: #e74c3c;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            background-color: white;
            border-radius: 0 0 12px 12px;
            overflow: hidden;
            box-shadow: 0 4px 15px rgba(0,0,0,0.05);
            margin-top: 15px;
        }
        th {
            background-color: #34495e;
            color: white;
            padding: 12px 15px;
            text-align: left;
            font-size: 14px;
        }
        td {
            padding: 12px 15px;
            border-bottom: 1px solid #edf2f7;
            text-align: left;
            font-size: 14px;
        }
        tr:last-child td {
            border-bottom: none;
        }
        .amount-col {
            font-weight: bold;
            text-align: right;
            color: #c0392b;
        }
        .date-col {
            color: #7f8c8d;
            font-size: 12px;
        }
        .footer {
            margin-top: 25px;
            text-align: center;
            font-size: 11px;
            color: #bdc3c7;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Munandy Transport</h1>
        <p>Vehicle Expense Report • ${startDateStr} to ${endDateStr}</p>
    </div>

    <div class="summary-bar">
        <div class="summary-label">Total Expenses</div>
        <div class="summary-value">$${totalAmount.toFixed(2)}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 120px;">Date</th>
                <th style="width: 120px;">Vehicle</th>
                <th>Description</th>
                <th style="width: 100px; text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            ${expenses.map(exp => {
                const dateObj = new Date(exp.expense_date);
                const displayDate = dateObj.toLocaleDateString('en-GB'); // dd/mm/yyyy
                return `
                <tr>
                    <td class="date-col">${displayDate}</td>
                    <td>${exp.vehicle_registration}</td>
                    <td>${exp.description}</td>
                    <td class="amount-col">$${Number(exp.amount).toFixed(2)}</td>
                </tr>
                `;
            }).join('')}
        </tbody>
    </table>

    <div class="footer">
        Generated by Munandy Transport Bot • ${new Date().toLocaleString('en-ZA')}
    </div>
</body>
</html>
    \`;

    return await nodeHtmlToImage({
        html: htmlTemplate,
        quality: 100,
        type: 'png',
        puppeteerArgs: {
            args: ['--no-sandbox', '--disable-setuid-sandbox'],
        },
    });
}

module.exports = { generateExpenseImageReport };
